version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --with docs
    - poetry run sphinx-build -b html docs/source "$READTHEDOCS_OUTPUT/html"

sphinx:
  configuration: docs/source/conf.py
