name: "Check reminders"

on:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check reminders and notify
        uses: agrc/reminder-action@v1
