name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest

      - name: Install dependencies
        run: |
          poetry install --with tests

      - name: Run tests
        run: |
          poetry run pytest
